# Generated by Django 4.1.7 on 2023-02-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyagebooksapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='user',
        ),
    ]
